### ISSUE TITLE
Installing Plugin

### ISSUE THREAD

**Issue by DevShah** [jprante/elasticsearch-analysis-naturalsort#10]
I'm fairly new to elasticsearch so I apologize in advance for any obvious questions. I'm getting some issues when following your example documentation. After installing the plugin, I create the index, and then perform the query which results in 
```Parse Failure [No mapping found for [points.sort] in order to sort on]```. 
I know the plugin is installed because by running ```curl -XGET 'http://localhost:9200/_nodes/_all'``` I receive
 ```"plugins":[{"name":"analysis-naturalsort-1.3.4.0-0dc9d9d","version":"1.3.4.0","description":"Natural Sort Key Analysis","jvm":true,"site":false}```

 I'm running elasticsearch-1.3.8. I also tried including it in a rails model index, and the response I receive when recreating an index is - 
```MapperParsingException[Analyzer [naturalsort] not found for field [natural_sort]];```

**Comment by jprante** [comment]
1.3 is pretty old, and docs may not be valid for such old versions. Can you update?

**Comment by DevShah** [comment]
Got it to work using your old readme - thank you.
