### ISSUE TITLE
5.x compatibility

### ISSUE THREAD

**Issue by danwkennedy** [jprante/elasticsearch-analysis-naturalsort#13]
We'd like to use this with the 5.x series of ES especially since 5.1.1 is out. Do you know if the current state of this plugin can support it?

**Comment by jprante** [comment]
No, it will not.

ES 5.x plugin development is currently at https://github.com/jprante/elasticsearch-plugin-bundle/tree/5.0

See https://github.com/jprante/elasticsearch-plugin-bundle/tree/5.0/src/main/java/org/xbib/elasticsearch/index/analysis/naturalsort

I can derive a ES 5.x version of elasticsearch-analysis-naturalsort

**Comment by danwkennedy** [comment]
Is this where development is going to happen moving forward?

**Comment by jprante** [comment]
I offer two flavors, single plugins, and a bundle of my plugins for convenience. The bundle is larger and includes a GPL project, so I keep going with the single plugin approach.

**Comment by jprante** [comment]
Version 5.1.1.0 released.
