### ISSUE TITLE
What versions of ES is this compatible with?

### ISSUE THREAD

**Issue by bbehling** [jprante/elasticsearch-analysis-naturalsort#7]
Documented as only supported only for 1.4.0 and 1.2.1. Will this work on version 1.3.4?

Or this supports for version 1.2.1 through 1.4.0?

**Comment by jprante** [comment]
It is not ready for 1.3.4, but I can build a version for this.

**Comment by bbehling** [comment]
That would be great.

We have a big need for a natural sort feature in ES.

**Comment by jprante** [comment]
I have pushed a plugin version 1.3.4.0 for ES 1.3.4

**Comment by bbehling** [comment]
Thank you very much!

**Comment by cjqed** [comment]
How difficult would it be to make this compatible with 1.6.0?

**Comment by jprante** [comment]
It should work on ES 1.6

I pushed new releases so the version numbers match (1.6.1.0, 1.7.0.0)
