### ISSUE TITLE
Sorting in Aggregate Returns Incorrect Characters

### ISSUE THREAD

**Issue by bbehling** [jprante/elasticsearch-analysis-naturalsort#8]
When sorting in an aggregate, the key values returned looks like wing ding characters.

Is there a way to get the correct value out instead of these characters?

query - 

{
  "query": {
    "match_all": {}
  },
  "size": 100,
  "aggs": {
    "distinct": {
      "terms": {
        "field": "values.sort",
        "order": {
          "_term": "asc"
        },
        "size": 100
      }
    }
  }
}

result -
"aggregations": {
    "distinct": {
        "buckets": [
            {"key": "$ 倀, "doc_count": 1},
            {"key": "$䀑怈怄怀", "doc_count": 1},
            ...
        ]
      }
  }

**Comment by jprante** [comment]
The sort key is binary encoded and can not be displayed in aggregations.
