### ISSUE TITLE
Compatibility with Elasticsearch 2.1.1?

### ISSUE THREAD

**Issue by ThisIsMissEm** [jprante/elasticsearch-analysis-naturalsort#9]
I'm currently running on elasticsearch 2.1.1, and would like to use this plugin, however, I note that the documentation only goes up to version 1.7.0 of elasticsearch.

Are there any plans to update this plugin?

**Comment by jprante** [comment]
I just released version 2.1.1.0 of the naturalsort plugin.

Note that token filter is gone. To use naturalsort, there is a pre-defined analyzer called "naturalsort".

**Comment by miksago** [comment]
Hi, thanks; I only realised afterwards that this is now covered by the icu-analysis plugin, as far as I can tell.

**Comment by nicolaiwolko** [comment]
Will there be a version for Elasticsearch 2.3.3 soon?

**Comment by jprante** [comment]
I just released 2.3.3.0 for Elasticsearch 2.3.3
